name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build NextJS app
        run: |
          npm install
          npm run build

      - name: Deploy to Google Cloud Storage
        uses: GoogleCloudPlatform/github-actions/deploy-cloud-storage@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          source: out
          destination: hades-bucket
